version: '3'
services:
  oracle-db:
    image: gvenzl/oracle-xe
    container_name: oracle
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: oracle
      APP_USER: devuser
      APP_USER_PASSWORD: devpass
